# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e519b7e8da21f3c1bbf0d1c5cba2393cd97c5e92940c60f594522cca3eafef373a8271e96ce60abc575c5913e8f26f05d5cddcb9f84188b3d9dcf0b0a855ee0

test:
  secret_key_base: 7e520740954cf33a17af9913884c964b4bed24132096b8e601196418c93083b46ce1cbf113a0a3ab278a0018f31a0a18f1783bf265bc149a6c43afd985eab8ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mail_username: "<%= ENV['MAIL_USERNAME'] %>"
  mail_password: "<%= ENV['MAIL_PASSWORD'] %>"
  mail_smtp_host: "<%= ENV['MAIL_SMTP_HOST'] %>"
  mail_port:  "<%= ENV['MAIL_PORT'] %>"
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
